version: '3'

services:
  php:
    env_file: .env
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    entrypoint: sh /bin/entrypoint.sh php-fpm
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./docker/php/entrypoint.sh:/bin/entrypoint.sh"
      - ./:/var/www
    links:
      - db:mysql
    expose:
      - 9000
  db:
    image: mysql:8
    ports:
       - "3306:3306"
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "db-data:/var/lib/mysql"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    ports:
      - 5426:80
    links:
      - db:db
    depends_on:
      - db
  nodejs:
    env_file: .env
    build: ./docker/nodejs
    container_name: ${APP_NAME}_nodejs
    restart: "no"
    entrypoint: sh /bin/entrypoint.sh
    volumes:
      - ./:/var/www/html
      - ./docker/nodejs/entrypoint.sh:/bin/entrypoint.sh
  apache:
    env_file: .env
    build: ./docker/httpd
    volumes:
      - "./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - ./:/var/www
    depends_on:
      - php
    expose:
      - 8080
  web:
    env_file: .env
    build: ./docker/nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - 8000:80
    restart: always
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/app.conf:/etc/nginx/sites-available/application.conf"
      - "./docker/nginx/app.conf:/etc/nginx/sites-enabled/application"
      - "./docker/log/nginx:/var/log/nginx"
      - ./:/var/www
    depends_on:
      - apache

volumes:
  db-data: ~